/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto4;

import java.awt.Color;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Stack;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.graphstream.graph.implementations.SingleGraph;

import org.graphstream.algorithm.Dijkstra;
import org.graphstream.algorithm.Kruskal;
import org.graphstream.algorithm.generator.DorogovtsevMendesGenerator;

import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author milton
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    private guardar save = new guardar();
    private Graph g;

    public principal() {

        initComponents();
        /*FileOutputStream outFile;
        save.setUsuario(new persona("root", "root123",null));
            try {
                outFile = new FileOutputStream("Amigos.gamil");
                try {
                    ObjectOutputStream outObject = new ObjectOutputStream(outFile);
                    outObject.writeObject(save);
                } catch (IOException ex) {

                }
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
         
         */
        FileInputStream inFile;
        try {
            inFile = new FileInputStream("Amigos.gamil");
            ObjectInputStream inputObject = new ObjectInputStream(inFile);
            Object objeto = inputObject.readObject();
            if (objeto instanceof guardar) {
                save = (guardar) objeto;
                for (int i = 0; i < save.getUsuarios().getSize(); i++) {
                    persona temp = (persona) save.getUsuarios().get(i);

                }
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        tf_usuarioRegistro = new javax.swing.JTextField();
        jp_passwordRegistro = new javax.swing.JPasswordField();
        bt_registro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jd_perfil = new javax.swing.JDialog();
        jt_usuarioPerfil = new javax.swing.JTabbedPane();
        jp_perfil = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jp_amigos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl__personas = new javax.swing.JList<>();
        bt_enviarSolicitud = new javax.swing.JButton();
        jp_mensajes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_mensajes = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_verMensaje = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_responderMensaje = new javax.swing.JTextArea();
        ta_enviarMensaje = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_menu = new javax.swing.JMenu();
        jmi_verMapa = new javax.swing.JMenuItem();
        jmi_cerrarSesion = new javax.swing.JMenuItem();
        jmi_conocerAmigos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmi_enviarMensaje = new javax.swing.JMenuItem();
        jd_mensaje = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_amigosMensajes = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_nuevoMensaje = new javax.swing.JTextArea();
        bt_enviarNuevoMensaje = new javax.swing.JButton();
        asunto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pm_profilepic = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jd_conocerA = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb_personaConocer = new javax.swing.JComboBox<>();
        bt_vermapa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jt_usuario = new javax.swing.JTextField();
        jp_contraseña = new javax.swing.JPasswordField();
        bt_login = new javax.swing.JButton();
        jl_registro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jd_registro.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_registroWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        jLabel2.setText("REGISTRO");

        bt_registro.setText("Registrarse");
        bt_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registroMouseClicked(evt);
            }
        });

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_registroLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_usuarioRegistro)))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jp_passwordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_usuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp_passwordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(bt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jd_perfil.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_perfilWindowClosing(evt);
            }
        });

        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_perfilLayout = new javax.swing.GroupLayout(jp_perfil);
        jp_perfil.setLayout(jp_perfilLayout);
        jp_perfilLayout.setHorizontalGroup(
            jp_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jp_perfilLayout.setVerticalGroup(
            jp_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jt_usuarioPerfil.addTab("Perfil", jp_perfil);

        jLabel7.setText("Tus amigos:");

        jScrollPane1.setViewportView(jl_amigos);

        jLabel8.setText("Personas que quizas conozcas:");

        jScrollPane2.setViewportView(jl__personas);

        bt_enviarSolicitud.setText("Enviar");
        bt_enviarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_enviarSolicitudMouseClicked(evt);
            }
        });
        bt_enviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_amigosLayout = new javax.swing.GroupLayout(jp_amigos);
        jp_amigos.setLayout(jp_amigosLayout);
        jp_amigosLayout.setHorizontalGroup(
            jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_amigosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jp_amigosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_enviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_amigosLayout.setVerticalGroup(
            jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_amigosLayout.createSequentialGroup()
                .addGroup(jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_amigosLayout.createSequentialGroup()
                        .addGroup(jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jp_amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_amigosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_amigosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(bt_enviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_amigosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_usuarioPerfil.addTab("Amigos", jp_amigos);

        jl_mensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_mensajesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_mensajes);

        ta_verMensaje.setColumns(20);
        ta_verMensaje.setRows(5);
        jScrollPane4.setViewportView(ta_verMensaje);

        ta_responderMensaje.setColumns(20);
        ta_responderMensaje.setRows(5);
        jScrollPane5.setViewportView(ta_responderMensaje);

        ta_enviarMensaje.setText("ENVIAR");
        ta_enviarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ta_enviarMensajeMouseClicked(evt);
            }
        });

        jLabel9.setText("Tus Mensajes:");

        jLabel17.setText("Mensaje:");

        javax.swing.GroupLayout jp_mensajesLayout = new javax.swing.GroupLayout(jp_mensajes);
        jp_mensajes.setLayout(jp_mensajesLayout);
        jp_mensajesLayout.setHorizontalGroup(
            jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_mensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_mensajesLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(jp_mensajesLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ta_enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_mensajesLayout.setVerticalGroup(
            jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_mensajesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(jp_mensajesLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_mensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(ta_enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jt_usuarioPerfil.addTab("Mensajes", jp_mensajes);

        jm_menu.setText("Ver");

        jmi_verMapa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jmi_verMapa.setText("Ver mapa de amigos");
        jmi_verMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_verMapaMouseClicked(evt);
            }
        });
        jmi_verMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verMapaActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_verMapa);

        jmi_cerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmi_cerrarSesion.setText("Cerrar sesión");
        jmi_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarSesionActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_cerrarSesion);

        jmi_conocerAmigos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmi_conocerAmigos.setText("Conocer amigos");
        jmi_conocerAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_conocerAmigosActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_conocerAmigos);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Kruskal ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jm_menu.add(jMenuItem2);

        jmi_enviarMensaje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmi_enviarMensaje.setText("Enviar Mensaje");
        jmi_enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_enviarMensajeActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_enviarMensaje);

        jMenuBar1.add(jm_menu);

        jd_perfil.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_perfilLayout = new javax.swing.GroupLayout(jd_perfil.getContentPane());
        jd_perfil.getContentPane().setLayout(jd_perfilLayout);
        jd_perfilLayout.setHorizontalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jt_usuarioPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE)
        );
        jd_perfilLayout.setVerticalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_perfilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jt_usuarioPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jd_mensaje.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd_mensajeWindowClosing(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        jLabel10.setText("ENVIAR NUEVO MENSAJE");

        jScrollPane6.setViewportView(jl_amigosMensajes);

        ta_nuevoMensaje.setColumns(20);
        ta_nuevoMensaje.setRows(5);
        jScrollPane7.setViewportView(ta_nuevoMensaje);

        bt_enviarNuevoMensaje.setText("ENVIAR");
        bt_enviarNuevoMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_enviarNuevoMensajeMouseClicked(evt);
            }
        });

        jLabel12.setText("Amigos:");

        jLabel13.setText("Asunto:");

        jLabel14.setText("Texto:");

        javax.swing.GroupLayout jd_mensajeLayout = new javax.swing.GroupLayout(jd_mensaje.getContentPane());
        jd_mensaje.getContentPane().setLayout(jd_mensajeLayout);
        jd_mensajeLayout.setHorizontalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_enviarNuevoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jd_mensajeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel10)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jd_mensajeLayout.setVerticalGroup(
            jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jd_mensajeLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_enviarNuevoMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addGroup(jd_mensajeLayout.createSequentialGroup()
                                .addGroup(jd_mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jMenuItem1.setText("Cambiar foto de perfil");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseEntered(evt);
            }
        });
        pm_profilepic.add(jMenuItem1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Mapa para conocer personas");

        jLabel16.setText("Elija la persona a quien quisiera conocer:");

        bt_vermapa.setText("VER MAPA");
        bt_vermapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_vermapaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_conocerALayout = new javax.swing.GroupLayout(jd_conocerA.getContentPane());
        jd_conocerA.getContentPane().setLayout(jd_conocerALayout);
        jd_conocerALayout.setHorizontalGroup(
            jd_conocerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_conocerALayout.createSequentialGroup()
                .addGroup(jd_conocerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_conocerALayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel15))
                    .addGroup(jd_conocerALayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(jd_conocerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_personaConocer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_vermapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jd_conocerALayout.setVerticalGroup(
            jd_conocerALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_conocerALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_personaConocer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_vermapa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        jLabel1.setText("MESSENGER ");
        jLabel1.setToolTipText("");

        bt_login.setText("ENTRAR");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });

        jl_registro.setText("haz click aqui para registrarte");
        jl_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jl_registroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jl_registroMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_registroMouseClicked(evt);
            }
        });

        jLabel3.setText("Nombre de usuario:");

        jLabel4.setText("contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_registro)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jp_contraseña)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_login)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_registro)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_registroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMousePressed
        jl_registro.setForeground(Color.BLUE);
    }//GEN-LAST:event_jl_registroMousePressed

    private void jl_registroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMouseReleased
        jl_registro.setForeground(Color.BLACK);
    }//GEN-LAST:event_jl_registroMouseReleased

    private void jl_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registroMouseClicked
        this.jd_registro.pack();
        this.jd_registro.setResizable(false);
        this.jd_registro.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jl_registroMouseClicked

    private void bt_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registroMouseClicked
        FileOutputStream outFile;
        String usuario = this.tf_usuarioRegistro.getText();
        String password = this.jp_passwordRegistro.getText();
        persona temp;
        boolean registrado = false;
        for (int i = 0; i < save.getUsuarios().getSize(); i++) {
            if (save.getUsuarios().get(i) instanceof persona) {
                temp = (persona) save.getUsuarios().get(i);
                if (temp.getUsuario().equals(usuario)) {
                    JOptionPane.showMessageDialog(this, "ya se ha registrado alguien con ese nombre!");
                    registrado = false;
                    break;
                } else {
                    registrado = true;
                }
            }
        }
        if (registrado == true) {
            JOptionPane.showMessageDialog(this.jd_registro, "Se ha podido registrar con exito!");
            save.setUsuario(new persona(usuario, password, null));
            tf_usuarioRegistro.setText("");
            jp_passwordRegistro.setText("");
            try {
                outFile = new FileOutputStream("Amigos.gamil");
                try {
                    ObjectOutputStream outObject = new ObjectOutputStream(outFile);
                    outObject.writeObject(save);
                } catch (IOException ex) {

                }
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
            this.jd_registro.dispose();
            this.show();
        }
    }//GEN-LAST:event_bt_registroMouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked

        persona temp;
        boolean logeado = true;
        for (int i = 0; i < save.getUsuarios().getSize(); i++) {
            if (save.getUsuarios().get(i) instanceof persona) {

                temp = (persona) save.getUsuarios().get(i);
                if (temp.getUsuario().equals(this.jt_usuario.getText()) && temp.getPassword().equals(this.jp_contraseña.getText())) {
                    JOptionPane.showMessageDialog(this, "Se ha logeado con exito!");

                    jt_usuario.setText("");
                    jp_contraseña.setText("");
                    this.jd_perfil.pack();
                    this.jd_perfil.setResizable(false);
                    this.jd_perfil.setVisible(true);
                    this.hide();
                    DefaultListModel model = new DefaultListModel();
                    DefaultListModel model2 = new DefaultListModel();
                    model3 = new DefaultListModel();
                    jl_mensajes.setModel(model3);
                    jl_amigos.setModel(model2);
                    this.jl__personas.setModel(model);
                    LinkedList aux = temp.getAmigos();
                    LinkedList aux3 = temp.getMensajes();
                    Stack sinLeer = temp.getPila();
                    for (int j = 0; j < sinLeer.size(); j++) {
                        Mensaje mensaje = (Mensaje) sinLeer.get(j);
                        persona person = (persona) mensaje.getAutor();
                        model3.addElement(mensaje.getAsunto() + " - " + person.getUsuario() + "- Sin leer");
                    }
                    for (int j = 0; j < aux3.getSize(); j++) {
                        Mensaje mensaje = (Mensaje) aux3.get(j);
                        persona person = (persona) mensaje.getAutor();
                        model3.addElement(mensaje.getAsunto() + " - " + person.getUsuario() + "- Leido");
                    }
                    for (int j = 0; j < aux.getSize(); j++) {
                        persona aux2 = (persona) temp.getAmigos().get(j);
                        model2.addElement(aux2.getUsuario());
                    }
                    for (int j = 0; j < save.getUsuarios().getSize(); j++) {
                        persona temp2 = (persona) save.getUsuarios().get(j);
                        if (!temp2.getUsuario().equals(temp.getUsuario())) {

                            model.addElement(temp2.getUsuario());
                        }
                    }
                    seleccionado = temp;
                    jl__personas.setModel(model);
                    jl_amigos.setModel(model2);
                    jl_mensajes.setModel(model3);
                    logeado = true;

                    break;
                } else {
                    logeado = false;
                }
            }
        }
        if (logeado == false) {
            JOptionPane.showMessageDialog(this, "Ingrese un usuario y contraseña valido");
        }
    }//GEN-LAST:event_bt_loginMouseClicked

    private void jmi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarSesionActionPerformed
        this.jd_perfil.dispose();
        this.show();
    }//GEN-LAST:event_jmi_cerrarSesionActionPerformed

    private void jmi_enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_enviarMensajeActionPerformed
        this.jd_mensaje.pack();
        this.jd_mensaje.setResizable(false);
        DefaultListModel model = new DefaultListModel();
        jl_amigosMensajes.setModel(model);
        for (int i = 0; i < seleccionado.getAmigos().getSize(); i++) {
            persona temp = (persona) seleccionado.getAmigos().get(i);
            model.addElement(temp.getUsuario());
        }
        jl_amigosMensajes.setModel(model);
        this.jd_mensaje.setVisible(true);
        this.jd_perfil.hide();
    }//GEN-LAST:event_jmi_enviarMensajeActionPerformed

    private void jd_registroWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_registroWindowClosing
        // TODO add your handling code here:
        this.show();
    }//GEN-LAST:event_jd_registroWindowClosing

    private void jd_perfilWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_perfilWindowClosing
        // TODO add your handling code here:
        this.show();
    }//GEN-LAST:event_jd_perfilWindowClosing

    private void jd_mensajeWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd_mensajeWindowClosing
        // TODO add your handling code here:
        this.jd_perfil.show();
    }//GEN-LAST:event_jd_mensajeWindowClosing

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        if (!evt.isMetaDown()) {
            this.pm_profilepic.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jMenuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseEntered
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int res = chooser.showOpenDialog(principal.this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getAbsolutePath());
            Rectangle rect = this.jLabel11.getBounds();
            Image icon = image.getImage().getScaledInstance(rect.width, rect.height, rect.width);
            image = new ImageIcon(icon);
            jLabel11.setIcon(image);
        }
    }//GEN-LAST:event_jMenuItem1MouseEntered

    private void bt_enviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarSolicitudActionPerformed


    }//GEN-LAST:event_bt_enviarSolicitudActionPerformed

    private void bt_enviarSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_enviarSolicitudMouseClicked
        String search = this.jl__personas.getSelectedValue();
        LinkedList aux = seleccionado.getAmigos();
        persona temp1;
        boolean pass = true;
        for (int i = 0; i < aux.getSize(); i++) {
            temp1 = (persona) aux.get(i);
            if (temp1.getUsuario().equals(search)) {
                pass = false;
                break;
            }
        }
        if (pass) {
            for (int j = 0; j < save.getUsuarios().getSize(); j++) {
                persona temp = (persona) save.getUsuarios().get(j);
                if (temp.getUsuario().equals(search)) {

                    seleccionado.setAmigo(temp);
                    temp.setAmigo(seleccionado);
                    save.replace(seleccionado);
                    save.replace(temp);
                    DefaultListModel model = new DefaultListModel();
                    model.addElement(temp.getUsuario());
                    jl_amigos.setModel(model);

                    //System.out.println("hola");
                    Guardar();
                    break;
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_enviarSolicitudMouseClicked

    private void bt_enviarNuevoMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_enviarNuevoMensajeMouseClicked
        if (!ta_nuevoMensaje.getText().equals("") && !asunto.getText().equals("")) {
            persona temp = null;
            persona enviar = null;
            for (int i = 0; i < seleccionado.getAmigos().getSize(); i++) {
                temp = (persona) seleccionado.getAmigos().get(i);
                if (temp.getUsuario().equals(jl_amigosMensajes.getSelectedValue())) {
                    enviar = temp;
                }
            }
            enviar.setMensaje(new Mensaje(ta_nuevoMensaje.getText(), seleccionado, asunto.getText()));
            //System.out.println(ta_nuevoMensaje.getT);
            save.replace(enviar);
            asunto.setText("");
            ta_nuevoMensaje.setText("");
            Guardar();
        }
    }//GEN-LAST:event_bt_enviarNuevoMensajeMouseClicked

    private void jl_mensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_mensajesMouseClicked
        LinkedList aux = seleccionado.getMensajes();
        Stack aux2 = seleccionado.getPila();
        Stack aux3 = new Stack();
        for (int i = 0; i < seleccionado.getMensajes().size; i++) {
            Mensaje temp = (Mensaje) aux.get(i);
            persona person = (persona) temp.getAutor();
            if (jl_mensajes.getSelectedValue().equals(temp.getAsunto() + " - " + person.getUsuario() + "- Leido")) {
                ta_verMensaje.setText(temp.getMensaje());
                break;
            }
        }
        for (int i = aux2.size() - 1; i >= 0; i--) {
            Mensaje temp = (Mensaje) aux2.pop();
            persona person = (persona) temp.getAutor();
            if (!jl_mensajes.getSelectedValue().equals(temp.getAsunto() + " - " + person.getUsuario() + "- Sin leer")) {
                aux3.push(temp);
            } else {
                seleccionado.mensajeLeido(temp);
                ta_verMensaje.setText(temp.getMensaje());
               // jl_mensajes.remove(jl_mensajes.getSelectedIndex());
                model3.remove(jl_mensajes.getSelectedIndex());
                this.model3.addElement(temp.getAsunto() + " - " + person.getUsuario() + " - Leido");
                jl_mensajes.setModel(model3);
                //jl_mensajes.setSelectedValue(temp.getAsunto() + " - " + person.getUsuario() + " - Leido", false);
            }
        }
        seleccionado.setPila(aux3);
        Guardar();
    }//GEN-LAST:event_jl_mensajesMouseClicked

    private void ta_enviarMensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ta_enviarMensajeMouseClicked
        LinkedList aux = seleccionado.getMensajes();
        Mensaje temp = null;
        for (int i = 0; i < seleccionado.getMensajes().size; i++) {
            temp = (Mensaje) aux.get(i);
            if (jl_mensajes.getSelectedValue().equals(temp.getAsunto() + " - " + temp.getAutor())) {
                ta_verMensaje.setText(temp.getMensaje());
                break;
            }
        }

        persona buscar = (persona) temp.getAutor();
        for (int i = 0; i < save.getUsuarios().size; i++) {
            persona temp1 = (persona) save.getUsuarios().get(i);
            if (buscar.getUsuario().equals(temp1.getUsuario())) {
                temp1.setMensaje(new Mensaje(ta_responderMensaje.getText(), temp.getAutor(), "RE: " + temp.getAsunto()));
                save.replace(temp1);
                ta_responderMensaje.setText("");
                Guardar();
                break;
            } else if (i == save.getUsuarios().size - 1) {
                JOptionPane.showMessageDialog(this, "no se ha podido enviar el mensaje");
            }
        }
    }//GEN-LAST:event_ta_enviarMensajeMouseClicked

    private void jmi_verMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verMapaActionPerformed
        g = new SingleGraph("ja");
        g.clear();
        g.setAutoCreate(false);
        g.setStrict(false);
        g.addNode(seleccionado.getUsuario()).setAttribute("ui.label", seleccionado.getUsuario());

        for (int i = 0; i < seleccionado.getAmigos().size; i++) {
            persona temp = (persona) seleccionado.getAmigos().get(i);
            g.addNode(temp.getUsuario()).setAttribute("ui.label", temp.getUsuario());
            g.addEdge(seleccionado.getUsuario() + "-" + temp.getUsuario(), seleccionado.getUsuario(), temp.getUsuario(), true).setAttribute("Relacion", i);
            for (int j = 0; j < temp.getAmigos().size; j++) {
                persona temp2 = (persona) temp.getAmigos().get(j);
                g.addNode(temp2.getUsuario()).setAttribute("ui.label", temp2.getUsuario());
                double valor = 1.00;
                String aux = temp.getUsuario(), aux2 = temp2.getUsuario();
                System.out.println(aux + aux2);

                g.addEdge(aux + "-" + aux2, aux, aux2, true).setAttribute("Relacion", j);

            }
        }
        g.display().setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
    }//GEN-LAST:event_jmi_verMapaActionPerformed

    private void jmi_verMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_verMapaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_verMapaMouseClicked

    private void jmi_conocerAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_conocerAmigosActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < save.getUsuarios().getSize(); i++) {
            persona temp = (persona) save.getUsuarios().get(i);

            System.out.println(temp.getUsuario());
            model.addElement(temp.getUsuario());

        }
        this.cb_personaConocer.setModel(model);
        this.jd_conocerA.pack();
        this.jd_conocerA.setResizable(false);
        this.jd_conocerA.setVisible(true);
    }//GEN-LAST:event_jmi_conocerAmigosActionPerformed

    private void bt_vermapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_vermapaMouseClicked
        // TODO add your handling code here:
        boolean continuar = true;
        String personaSeleccionada = this.cb_personaConocer.getSelectedItem().toString();
        for (int i = 0; i < seleccionado.getAmigos().getSize(); i++) {
            persona temp = (persona) seleccionado.getAmigos().get(i);
            if (temp.getUsuario().equals(personaSeleccionada)) {
                JOptionPane.showMessageDialog(this.jd_conocerA, "Ustedes ya son amigos");
                continuar = true;
                break;
            } else {

                continuar = false;
            }
        }
        if (!continuar) {
            this.Dijkstra(seleccionado.getUsuario(), personaSeleccionada, "Relacion");
        }
    }//GEN-LAST:event_bt_vermapaMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        /*utilizando el algoritmo de Kruskal proporcionado por la liberia de graphstream
        sacamos el arbol recubridor minimo del grafo de amigos de cada persona*/
        DorogovtsevMendesGenerator gen = new DorogovtsevMendesGenerator();
        String css = "edge .notintree {size:1px;fill-color:gray;} " +
				 "edge .intree {size:3px;fill-color:black;}";
        g.addAttribute("ui.stylesheet", css);
        this.g.display().setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
	 	Kruskal kruskal = new Kruskal("ui.class", "intree", "notintree");
	 
	 	kruskal.init(g);
	 	kruskal.compute();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asunto;
    private javax.swing.JButton bt_enviarNuevoMensaje;
    private javax.swing.JButton bt_enviarSolicitud;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_registro;
    private javax.swing.JButton bt_vermapa;
    private javax.swing.JComboBox<String> cb_personaConocer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JDialog jd_conocerA;
    private javax.swing.JDialog jd_mensaje;
    private javax.swing.JDialog jd_perfil;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JList<String> jl__personas;
    private javax.swing.JList<String> jl_amigos;
    private javax.swing.JList<String> jl_amigosMensajes;
    private javax.swing.JList<String> jl_mensajes;
    private javax.swing.JLabel jl_registro;
    private javax.swing.JMenu jm_menu;
    private javax.swing.JMenuItem jmi_cerrarSesion;
    private javax.swing.JMenuItem jmi_conocerAmigos;
    private javax.swing.JMenuItem jmi_enviarMensaje;
    private javax.swing.JMenuItem jmi_verMapa;
    private javax.swing.JPanel jp_amigos;
    private javax.swing.JPasswordField jp_contraseña;
    private javax.swing.JPanel jp_mensajes;
    private javax.swing.JPasswordField jp_passwordRegistro;
    private javax.swing.JPanel jp_perfil;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JTabbedPane jt_usuarioPerfil;
    private javax.swing.JPopupMenu pm_profilepic;
    private javax.swing.JButton ta_enviarMensaje;
    private javax.swing.JTextArea ta_nuevoMensaje;
    private javax.swing.JTextArea ta_responderMensaje;
    private javax.swing.JTextArea ta_verMensaje;
    private javax.swing.JTextField tf_usuarioRegistro;
    // End of variables declaration//GEN-END:variables
    persona seleccionado;
    DefaultListModel model3;

    void Guardar() {
        try {
            FileOutputStream outFile = new FileOutputStream("Amigos.gamil");
            try {
                ObjectOutputStream outObject = new ObjectOutputStream(outFile);
                outObject.writeObject(save);
            } catch (IOException ex) {

            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }

    public String Dijkstra(String logeado, String buscando, String valor) {
        String imprimir = "";
        try {
            for (int i = 0; i < g.getNodeCount(); i++) {
                g.getNode(i).addAttribute("ui.style", "fill-color: black;");
            }
            Dijkstra dijkstra = new Dijkstra(Dijkstra.Element.EDGE, null, valor + "");
            // Compute the shortest paths in g from A to all nodes
            dijkstra.init(g);
            dijkstra.setSource(g.getNode(logeado));
            dijkstra.compute();
            // Print the lengths of all the shortest paths
            /*for (Node node : g) {
            System.out.printf("%s->xD%s:%10.2f%n", dijkstra.getSource(), node,
                    dijkstra.getPathLength(node));
        }*/
            // Color in blue all the nodes on the shortest path form A to B
            for (Node node : dijkstra.getPathNodes(g.getNode(buscando))) {
                node.addAttribute("ui.style", "fill-color: blue;");
            }

            // Color in red all the edges in the shortest path tree
            // Print the shortest path from A to B
            imprimir = dijkstra.getPath(g.getNode(buscando)) + "";
            dijkstra.clear();
            System.out.println(imprimir);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado ningun grafo");
        }
        return imprimir;
    }

}
